basePath: /
host: localhost:3000
info:
  contact:
    email: support@qotera.com
    name: API Support
  description: Qotera Expense Intelligence Platform API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Qotera API
  version: "1.0"
paths: {}
swagger: "2.0"
